"""
Safety compliance rules engine for PPE detection.

Phase 3: Evaluate worker PPE compliance based on detection results and safety policy.
"""

import yaml
import logging
from collections import deque
from typing import Dict, List, Tuple, Optional, Deque
from dataclasses import dataclass, asdict
from enum import Enum


logger = logging.getLogger(__name__)


class AlertSeverity(Enum):
    """Alert severity levels."""
    INFO = "INFO"
    WARN = "WARN"
    CRITICAL = "CRITICAL"


@dataclass
class DetectionResult:
    """Single object detection result."""
    class_name: str
    class_id: int
    confidence: float
    bbox: Tuple[float, float, float, float]  # (x1, y1, x2, y2)
    area_pixels: Optional[int] = None


@dataclass
class Alert:
    """Safety alert generated by compliance check."""
    severity: AlertSeverity
    message: str
    equipment_type: Optional[str] = None
    worker_id: Optional[int] = None
    frame_idx: Optional[int] = None


@dataclass
class ComplianceResult:
    """Compliance evaluation result for a worker."""
    worker_id: int
    is_compliant: bool
    detected_equipment: Dict[str, float]  # {equipment: confidence}
    missing_equipment: List[str]
    alerts: List[Alert]
    confidence_score: float  # 0-1, percentage of required PPE detected


class SafetyRulesEngine:
    """Evaluate PPE compliance based on detection results."""

    def __init__(self, config_path: str,
                 temporal_window: int = 0,
                 alert_cooldown_frames: int = 30):
        """
        Initialize rules engine from configuration.

        Args:
            config_path: Path to compliance_rules.yaml
            temporal_window: If > 0, smooth confidence over last N frames per worker.
                             Reduces false alerts from single missed detections.
            alert_cooldown_frames: Suppress re-firing the same alert for this many frames.
        """
        self.config_path = config_path
        self.temporal_window = temporal_window
        self.alert_cooldown_frames = alert_cooldown_frames

        # Load configuration
        with open(config_path, 'r') as f:
            self.config = yaml.safe_load(f)

        # Extract key settings
        self.required_ppe = self.config.get('required_ppe', {})
        self.confidence_thresholds = self.config.get('confidence_thresholds', {})
        self.alerts_config = self.config.get('alerts', {})
        self.special_cases = self.config.get('special_cases', {})

        # Per-worker detection history for temporal smoothing
        # {worker_id: deque of {class_name: confidence} dicts}
        self._detection_history: Dict[int, Deque[Dict[str, float]]] = {}

        # Alert cooldown: {(worker_id, equipment_type): last_alert_frame}
        self._alert_last_frame: Dict[Tuple[int, str], int] = {}

        logger.info(
            f"Loaded safety rules from {config_path} "
            f"(temporal_window={temporal_window}, alert_cooldown={alert_cooldown_frames})"
        )

    def _update_history(self, worker_id: int, raw_detected: Dict[str, float]):
        """Update per-worker detection rolling window."""
        if worker_id not in self._detection_history:
            self._detection_history[worker_id] = deque(maxlen=self.temporal_window)
        self._detection_history[worker_id].append(raw_detected)

    def _smooth_detections(self, worker_id: int, current: Dict[str, float]) -> Dict[str, float]:
        """Return max-confidence over the temporal window (current frame + history)."""
        history = self._detection_history.get(worker_id, deque())
        smoothed: Dict[str, float] = dict(current)
        for past in history:
            for cls, conf in past.items():
                if conf > smoothed.get(cls, 0.0):
                    smoothed[cls] = conf
        return smoothed

    def _should_fire_alert(self, worker_id: int, equipment_type: str,
                           frame_idx: Optional[int]) -> bool:
        """Return True only if the alert cooldown has elapsed."""
        if frame_idx is None or self.alert_cooldown_frames <= 0:
            return True
        key = (worker_id, equipment_type)
        last = self._alert_last_frame.get(key, -self.alert_cooldown_frames - 1)
        if (frame_idx - last) >= self.alert_cooldown_frames:
            self._alert_last_frame[key] = frame_idx
            return True
        return False

    def evaluate_worker(self,
                        worker_id: int,
                        detections: List[DetectionResult],
                        frame_idx: Optional[int] = None) -> ComplianceResult:
        """
        Evaluate if a worker is compliant based on detected equipment.

        Args:
            worker_id: Unique worker identifier
            detections: List of DetectionResult (PPE items detected on this worker)
            frame_idx: Frame index (for logging/alerts)

        Returns:
            ComplianceResult with compliance status and details
        """
        raw_detected: Dict[str, float] = {}
        alerts = []

        # Filter detections by confidence threshold
        for detection in detections:
            class_name = detection.class_name
            confidence = detection.confidence

            # Get per-class threshold
            min_confidence = self.confidence_thresholds.get('equipment_specific', {}).get(
                class_name,
                self.confidence_thresholds.get('global_min', 0.25)
            )

            if confidence >= min_confidence:
                raw_detected[class_name] = confidence

        # Temporal smoothing: merge current frame with rolling history
        if self.temporal_window > 0:
            self._update_history(worker_id, raw_detected)
            detected_equipment = self._smooth_detections(worker_id, raw_detected)
        else:
            detected_equipment = raw_detected

        # Check for required PPE
        missing_equipment = []
        is_compliant = True

        # Eye protection
        eye_ok = self._check_category(
            detected_equipment,
            'safety_glasses', 'safety_goggles',
            category_name='eye_protection',
            alerts=alerts, worker_id=worker_id, frame_idx=frame_idx,
        )
        if not eye_ok:
            missing_equipment.extend(['safety_glasses', 'safety_goggles'])
            is_compliant = False

        # Head protection
        head_ok = self._check_category(
            detected_equipment,
            'hard_hat',
            category_name='head_protection',
            alerts=alerts, worker_id=worker_id, frame_idx=frame_idx,
            exclude=['regular_hat'],
        )
        if not head_ok:
            missing_equipment.append('hard_hat')
            is_compliant = False

        # Torso protection
        torso_ok = self._check_category(
            detected_equipment,
            'hi_vis_vest',
            category_name='torso_protection',
            alerts=alerts, worker_id=worker_id, frame_idx=frame_idx,
        )
        if not torso_ok:
            missing_equipment.append('hi_vis_vest')
            is_compliant = False

        # Foot protection
        foot_ok = self._check_category(
            detected_equipment,
            'work_boots',
            category_name='foot_protection',
            alerts=alerts, worker_id=worker_id, frame_idx=frame_idx,
            exclude=['regular_shoes'],
        )
        if not foot_ok:
            missing_equipment.append('work_boots')
            is_compliant = False

        # Calculate confidence score (% of required items detected)
        num_required = 4  # Eye, Head, Torso, Foot
        num_detected = sum(1 for item in [eye_ok, head_ok, torso_ok, foot_ok] if item)
        confidence_score = num_detected / num_required

        return ComplianceResult(
            worker_id=worker_id,
            is_compliant=is_compliant,
            detected_equipment=detected_equipment,
            missing_equipment=missing_equipment,
            alerts=alerts,
            confidence_score=confidence_score
        )

    def _check_category(self,
                       detected_equipment: Dict[str, float],
                       *options,
                       category_name: str,
                       alerts: List[Alert],
                       worker_id: int,
                       frame_idx: Optional[int] = None,
                       exclude: Optional[List[str]] = None) -> bool:
        """
        Check if any item from a category is detected.

        Args:
            detected_equipment: Detected items with confidence
            *options: PPE item names to check (e.g., 'safety_glasses', 'safety_goggles')
            category_name: Category name (e.g., 'eye_protection')
            alerts: Alert list to append to
            worker_id: Worker ID for alerts
            frame_idx: Frame index for alerts
            exclude: Items to explicitly exclude

        Returns:
            True if required item detected, False otherwise
        """
        exclude = exclude or []

        # Check if any option is detected
        for option in options:
            if option not in exclude and option in detected_equipment:
                return True

        # Not detected — fire alert only if cooldown has elapsed
        if self._should_fire_alert(worker_id, category_name, frame_idx):
            severity = self._get_alert_severity(category_name)
            alert = Alert(
                severity=severity,
                message=f"Worker {worker_id}: Missing {category_name}",
                equipment_type=category_name,
                worker_id=worker_id,
                frame_idx=frame_idx,
            )
            alerts.append(alert)

        return False

    def _get_alert_severity(self, equipment_category: str) -> AlertSeverity:
        """Map equipment category to alert severity."""
        severity_map = {
            'eye_protection': AlertSeverity.WARN,
            'head_protection': AlertSeverity.CRITICAL,  # Most critical
            'torso_protection': AlertSeverity.WARN,
            'foot_protection': AlertSeverity.INFO,
        }
        return severity_map.get(equipment_category, AlertSeverity.WARN)

    def evaluate_frame(self,
                      frame_detections: Dict[int, List[DetectionResult]],
                      frame_idx: int) -> Dict[int, ComplianceResult]:
        """
        Evaluate compliance for all workers in a frame.

        Args:
            frame_detections: {worker_id: [detections]}
            frame_idx: Frame index

        Returns:
            {worker_id: ComplianceResult}
        """
        frame_results = {}

        for worker_id, detections in frame_detections.items():
            result = self.evaluate_worker(worker_id, detections, frame_idx)
            frame_results[worker_id] = result

        return frame_results

    def evaluate_video(self,
                      video_results: Dict[int, Dict[int, List[DetectionResult]]]) -> Dict:
        """
        Evaluate compliance across entire video.

        Args:
            video_results: {frame_idx: {worker_id: [detections]}}

        Returns:
            Summary statistics
        """
        total_frames = len(video_results)
        total_workers = set()
        total_alerts = []
        frame_compliance_rates = []

        for frame_idx in sorted(video_results.keys()):
            frame_detections = video_results[frame_idx]
            frame_results = self.evaluate_frame(frame_detections, frame_idx)

            # Track workers
            total_workers.update(frame_results.keys())

            # Calculate per-frame compliance rate
            if frame_results:
                compliant_count = sum(1 for r in frame_results.values() if r.is_compliant)
                compliance_rate = compliant_count / len(frame_results)
                frame_compliance_rates.append(compliance_rate)

            # Collect alerts
            for worker_id, result in frame_results.items():
                total_alerts.extend(result.alerts)

        # Calculate statistics
        avg_compliance_rate = sum(frame_compliance_rates) / len(frame_compliance_rates) if frame_compliance_rates else 0
        critical_alerts = sum(1 for a in total_alerts if a.severity == AlertSeverity.CRITICAL)
        warn_alerts = sum(1 for a in total_alerts if a.severity == AlertSeverity.WARN)

        return {
            'total_frames': total_frames,
            'total_workers': len(total_workers),
            'avg_compliance_rate': avg_compliance_rate,
            'total_alerts': len(total_alerts),
            'critical_alerts': critical_alerts,
            'warn_alerts': warn_alerts,
            'frame_compliance_rates': frame_compliance_rates,
        }

    def format_compliance_report(self, compliance_result: ComplianceResult) -> str:
        """
        Format compliance result as readable report.

        Args:
            compliance_result: ComplianceResult object

        Returns:
            Formatted string report
        """
        status = "✓ COMPLIANT" if compliance_result.is_compliant else "✗ NON-COMPLIANT"

        report = f"\n{'='*60}\n"
        report += f"Worker {compliance_result.worker_id}: {status}\n"
        report += f"{'='*60}\n\n"

        report += "Detected Equipment:\n"
        if compliance_result.detected_equipment:
            for item, conf in sorted(compliance_result.detected_equipment.items()):
                report += f"  ✓ {item:25s} {conf:.2%}\n"
        else:
            report += "  (None detected)\n"

        report += "\nMissing Equipment:\n"
        if compliance_result.missing_equipment:
            for item in compliance_result.missing_equipment:
                report += f"  ✗ {item}\n"
        else:
            report += "  (None)\n"

        report += f"\nCompliance Score: {compliance_result.confidence_score:.1%}\n"

        if compliance_result.alerts:
            report += "\nAlerts:\n"
            for alert in compliance_result.alerts:
                report += f"  [{alert.severity.value}] {alert.message}\n"

        report += f"\n{'='*60}\n"

        return report

    def format_video_report(self, video_stats: Dict) -> str:
        """
        Format video-level compliance report.

        Args:
            video_stats: Video statistics from evaluate_video()

        Returns:
            Formatted string report
        """
        report = f"\n{'='*60}\n"
        report += "VIDEO COMPLIANCE SUMMARY\n"
        report += f"{'='*60}\n\n"

        report += f"Total Frames:          {video_stats['total_frames']:,}\n"
        report += f"Total Workers Detected: {video_stats['total_workers']:,}\n"
        report += f"Average Compliance:    {video_stats['avg_compliance_rate']:.1%}\n"
        report += f"Total Alerts:          {video_stats['total_alerts']:,}\n"
        report += f"  - Critical:          {video_stats['critical_alerts']:,}\n"
        report += f"  - Warnings:          {video_stats['warn_alerts']:,}\n"

        report += f"\n{'='*60}\n"

        return report


# Utility function for quick compliance checks
def check_worker_compliance(detections: List[DetectionResult], config_path: str) -> Tuple[bool, str]:
    """
    Quick compliance check for a worker.

    Args:
        detections: List of detected PPE items
        config_path: Path to compliance_rules.yaml

    Returns:
        (is_compliant, reason_string)
    """
    engine = SafetyRulesEngine(config_path)
    result = engine.evaluate_worker(worker_id=0, detections=detections)

    reason = "Compliant" if result.is_compliant else f"Missing: {', '.join(result.missing_equipment)}"

    return result.is_compliant, reason
